=== alexvzc/MiRouter/src/main/resources/mirouter-xsd/mirouter-xschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://xml.gda.itesm.mx/schemas/TC4003.1/mirouter/1"
           targetNamespace="http://xml.gda.itesm.mx/schemas/TC4003.1/mirouter/1"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="routes" type="tns:routes"/>
    <xs:complexType name="routes">
        <xs:sequence>
            <xs:element name="nodeName" type="xs:token"/>
            <xs:element name="nodePort" type="xs:short" minOccurs="0"/>
            <xs:element name="route" type="tns:route" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="route">
        <xs:sequence>
            <xs:element name="destination" type="xs:token"/>
            <xs:element name="nodeAddress" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="cost" type="xs:int"/>
            <xs:element name="link" type="xs:int" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="packet" type="tns:packet"/>
    <xs:complexType name="packet">
        <xs:sequence>
            <xs:element name="from" type="xs:token"/>
            <xs:element name="destination" type="xs:token"/>
            <xs:element name="visited" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== alexvzc/MiRouter/src/main/resources/node-e.xml
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns='http://xml.gda.itesm.mx/schemas/TC4003.1/mirouter/1'
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:schemaLocation='http://xml.gda.itesm.mx/schemas/TC4003.1/mirouter/1
        mirouter-xsd/mirouter-xschema.xsd'>
    <nodeName>E</nodeName>
    <nodePort>10105</nodePort>
    <route>
        <destination>B</destination>
        <cost>1</cost>
        <link>4</link>
    </route>
    <route>
        <destination>C</destination>
        <cost>1</cost>
        <link>5</link>
    </route>
    <route>
        <destination>D</destination>
        <cost>1</cost>
        <link>6</link>
    </route>
</routes>

=== alexvzc/MiRouter/src/main/resources/node-c.xml
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns='http://xml.gda.itesm.mx/schemas/TC4003.1/mirouter/1'
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:schemaLocation='http://xml.gda.itesm.mx/schemas/TC4003.1/mirouter/1
        mirouter-xsd/mirouter-xschema.xsd'>
    <nodeName>C</nodeName>
    <nodePort>10103</nodePort>
    <route>
        <destination>B</destination>
        <cost>1</cost>
        <link>2</link>
    </route>
    <route>
        <destination>E</destination>
        <nodeAddress>localhost:10105</nodeAddress>
        <cost>1</cost>
        <link>5</link>
    </route>
</routes>

=== alexvzc/MiRouter/src/main/resources/node-a.xml
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns='http://xml.gda.itesm.mx/schemas/TC4003.1/mirouter/1'
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:schemaLocation='http://xml.gda.itesm.mx/schemas/TC4003.1/mirouter/1
        mirouter-xsd/mirouter-xschema.xsd'>
    <nodeName>A</nodeName>
    <nodePort>10101</nodePort>
    <route>
        <destination>B</destination>
        <nodeAddress>localhost:10102</nodeAddress>
        <cost>1</cost>
        <link>1</link>
    </route>
    <route>
        <destination>D</destination>
        <nodeAddress>localhost:10104</nodeAddress>
        <cost>1</cost>
        <link>3</link>
    </route>
</routes>

=== alexvzc/MiRouter/src/main/resources/node-b.xml
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns='http://xml.gda.itesm.mx/schemas/TC4003.1/mirouter/1'
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:schemaLocation='http://xml.gda.itesm.mx/schemas/TC4003.1/mirouter/1
        mirouter-xsd/mirouter-xschema.xsd'>
    <nodeName>B</nodeName>
    <nodePort>10102</nodePort>
    <route>
        <destination>A</destination>
        <cost>1</cost>
        <link>1</link>
    </route>
    <route>
        <destination>C</destination>
        <nodeAddress>localhost:10103</nodeAddress>
        <cost>1</cost>
        <link>2</link>
    </route>
    <route>
        <destination>E</destination>
        <nodeAddress>localhost:10105</nodeAddress>
        <cost>1</cost>
        <link>4</link>
    </route>
</routes>
